[profile.default]
src = "contracts/src"
out = "out"
libs = ["lib"]
test = "contracts/test"
script = "contracts/script"
via_ir = true

remappings = [
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "@axiom-crypto/=lib/axiom-v2-periphery/",
    "@uniswap/v3-periphery/=lib/v3-periphery/",
    "@uniswap/v3-core/=lib/v3-core/"
]
